MODULE_NAME := sensor_jxf37pa_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)/jxf37pa

SRCS := $(DIR)/jxf37pa.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
